package JMRVideoExtension.iu;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;



public class Canvas extends javax.swing.JPanel {

    
    public Canvas() {
        initComponents();
    }
    
    /**
     * List of images that the canvas will contain
     */
    List<BufferedImage> imagesList = new ArrayList<>();
        
    
    /**
     * Set the content of the images list
     * @param images 
     */
    public void setImages(List<BufferedImage> images) {
        this.imagesList = images;
        for (BufferedImage img : images) {
            if (img != null) {
                setPreferredSize(new Dimension(img.getWidth(), img.getHeight()));
            }
        }
    }
    
    
    /**
     * Get list of canvas images
     * @return list of images
     */
    public List<BufferedImage> getImagesList(){
        return this.imagesList;
    }
    
    /**
     * Get an image from the canvas image list
     * @param index 
     * @return image
     */
    public BufferedImage getImagesList(int index){
        return this.imagesList.get(index);
    }
    
    
    /**
     * Resize canvas size
     */
    private void updatePreferredSize() {
        int width = 0;
        int height = 0;
        for (BufferedImage img : imagesList) {
            width += img.getWidth() + 15;
            height = Math.max(height, img.getHeight());
        }
        setPreferredSize(new Dimension(width, height+10));
        revalidate();                                                       // Required for the parent container to update the layout
    }
    
    
    /**
     * Paint the images on the canvas
     * @param g 
     */
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        
        int x = 5;
        updatePreferredSize();
        
        for (BufferedImage img : imagesList) {
            g2d.drawImage(img, x, 10, this);
            x += img.getWidth() + 15;
        }
             
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
