package JMRVideoExtension.iu;

import static JMRVideoExtension.App.resizeImage;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;



/**
 *
 * @author David Martinez Domingo
 */


public class InternalWindowMix extends javax.swing.JInternalFrame {
    
    /**
     * List of videos in the first row in the window
     */
    private final List<File> videoFiles;
    
    /**
     * List of images of the most similar videos from the DB
     */
    private final List<BufferedImage> images1;
    
    /**
     * List of images of the selected video
     */
    private final List<BufferedImage> images2;

    /**
     * Constructor 
     * @param videoFiles  List of videos in the first row in the window
     * @param images1 List of images of the most similar videos from the DB
     * @param images2 List of images of the selected video
     */
    public InternalWindowMix(List<File> videoFiles, List<BufferedImage> images1, List<BufferedImage> images2) {
        this.videoFiles = videoFiles;
        this.images1 = images1;
        this.images2 = images2;
        initComponents();
        initFrame();     
    }
    
    

    private void initFrame() {
    
        JPanel videoGridPanel = new JPanel(new GridLayout(3, videoFiles.size(),2,2));
     
        for (File videoFile : videoFiles) {                                         //Add video rows
            CanvasMix videoPanel = new CanvasMix(videoFile, videoNameLabel); 
            videoGridPanel.add(videoPanel);     
        }

        //Add row one 
        for (int i=0; i<=images1.size(); i++) {
            JPanel imagePanel = new JPanel();
            if(i>0){
                BufferedImage im = resizeImage(images1.get(i-1), 220,220);
                JLabel imageLabel = new JLabel(new ImageIcon(im));
                imagePanel.add(imageLabel);
            }
            videoGridPanel.add(imagePanel);
        }
        
        
        //Add row two
        for (int i=0; i<=images2.size(); i++) {
            JPanel imagePanel = new JPanel();
            if(i>0){
                BufferedImage im = resizeImage(images2.get(i-1), 220,220);
                JLabel imageLabel = new JLabel(new ImageIcon(im));
                imagePanel.add(imageLabel);
            }
            videoGridPanel.add(imagePanel);
        }
          
        getContentPane().add(videoGridPanel);
        pack();
        setVisible(true);
          
        JScrollPane scrollPane = new JScrollPane(videoGridPanel);
        getContentPane().add(scrollPane);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        videoNameLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        videoNameLabel.setText("Video: ");
        jPanel1.add(videoNameLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel videoNameLabel;
    // End of variables declaration//GEN-END:variables
}
