package JMRVideoExtension.iu;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;



public class Lienzo extends javax.swing.JPanel {

    
    public Lienzo() {
        initComponents();
    }
    
    /**
     * Lista de imagenes que contendra el lienzo
     */
    List<BufferedImage> imagesList = new ArrayList<>();
        
    
    /**
     * Establecer el contenido de la lista de imagenes
     * @param images 
     */
    public void setImages(List<BufferedImage> images) {
        this.imagesList = images;
        for (BufferedImage img : images) {
            if (img != null) {
                setPreferredSize(new Dimension(img.getWidth(), img.getHeight()));
            }
        }
    }
    
    
    /**
     * Obtener lista de imagenes del lienzo
     * @return Listado de imagenes
     */
    public List<BufferedImage> getImagesList(){
        return this.imagesList;
    }
    
    /**
     * Obtener una imagen de la lista de imagenes del lienzo
     * @param indice 
     * @return imagen correspondiente al indice
     */
    public BufferedImage getImagesList(int indice){
        return this.imagesList.get(indice);
    }
    
    
    /**
     * Redimensionar el tamaño del lienzo
     */
    private void updatePreferredSize() {
        int width = 0;
        int height = 0;
        for (BufferedImage img : imagesList) {
            width += img.getWidth() + 15;
            height = Math.max(height, img.getHeight());
        }
        setPreferredSize(new Dimension(width, height+10));
        revalidate();                                                           // Necesario para que el contenedor padre actualice el layout
    }
    
    
    /**
     * Pintar las imagenes en el lienzo
     * @param g 
     */
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        
        int x = 5;
        updatePreferredSize();
        
        for (BufferedImage img : imagesList) {
            g2d.drawImage(img, x, 10, this);
            x += img.getWidth() + 15;
        }
             
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
