package JMRVideoExtension.iu;



public class VentanaInterna extends javax.swing.JInternalFrame {

    public VentanaInterna() {
        initComponents();  
    }
    
    /**
     * Ventana interna de video que esta asociada (padre) de esta
     */
    VentanaInternaVideo viV_asociada;

    
    /**
     * Obtener lienzo
     * @return Lienzo
     */
    public Lienzo getLienzo() {
        return lienzo;
    }

    /**
     * Establecer nuevo lienzo
     * @param lienzo 
     */
    public void setLienzo(Lienzo lienzo) {
        this.lienzo = lienzo;
    }
    
    /**
     * Obtener ventana de video asociada a esta
     * @return VentanaInternaVideo
     */
    public VentanaInternaVideo getviV_asociada() {
        return viV_asociada;
    }

    /**
     * Establecer la ventana de video asociada a esta
     * @param viV_asociada 
     */
    public void setviV_asociada(VentanaInternaVideo viV_asociada) {
        this.viV_asociada = viV_asociada;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new JMRVideoExtension.iu.Lienzo();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private JMRVideoExtension.iu.Lienzo lienzo;
    // End of variables declaration//GEN-END:variables
}
