package JMRVideoExtension.iu;

import java.io.File;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayerEventListener;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 *
 * @author David Martinez Domingo
 */

public class VentanaInternaVideo extends javax.swing.JInternalFrame {

    /**
     * Reproductor multimedia
     */
    private EmbeddedMediaPlayer vlcplayer = null;
    
    /**
     * Video
     */
    private File video;
    
    
    /**
     * Inicializacion de parametros
     */
    public VentanaInternaVideo(File f) {
        initComponents();
        video = f;
        
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        getContentPane().add(aVisual,java.awt.BorderLayout.CENTER); 
        vlcplayer = aVisual.getMediaPlayer();
    }
    
   
  
    /**
     * Obtener la ventana interna de video asociada al video
     * @return Reproductor 
     */
    public static VentanaInternaVideo getInstance(File f){
        VentanaInternaVideo v = new VentanaInternaVideo(f);
        return (v.vlcplayer!=null?v:null); 
    }

    /**
     * Obtener lienzo
     * @return Lienzo
     */
    public Lienzo getLienzo() {
        return lienzo1;
    }

    /**
     * Establecer nuevo lienzo
     * @param lienzo 
     */
    public void setLienzo(Lienzo lienzo) {
        this.lienzo1 = lienzo;
    }
    
    /**
     * Obtener el video seleccionado
     * @return Video
     */
    public File getVideo() {
        return video;
    }

     /**
     * Establecer un nuevo video
     * @param video
     */
    public void setVideo(File video) {
        this.video = video;
    }
    
    /**
     * Obtener el reproductor multimedia
     * @return Reproductor 
     */
    public EmbeddedMediaPlayer getMediaPlayer() {
        return vlcplayer;
    }

    /**
     * El video comienza a reproducirse
     */
    public void play() {
        if (vlcplayer != null) {
            if(vlcplayer.isPlayable()){
                vlcplayer.mute(true);
                vlcplayer.play();
            } else {
                vlcplayer.playMedia(video.getAbsolutePath());
            }
        } 
    }
    
    /**
     * La reproduccion del video se detiene
     */
    public void stop() {
        if (vlcplayer != null) {
            if (vlcplayer.isPlaying()) {
                vlcplayer.pause();
            } else {
                vlcplayer.stop();
            }
        } 
    }
    
    
    /**
     * Añade un Listener al reproductor multimedia
     * @param ml 
     */
    public void addMediaPlayerEventListener(MediaPlayerEventListener ml) {
        if (vlcplayer != null) {
            vlcplayer.addMediaPlayerEventListener(ml);
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo1 = new JMRVideoExtension.iu.Lienzo();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private JMRVideoExtension.iu.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
